CREATE TABLE `beneficiaries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`application_id` int,
	`activity_id` int,
	`first_name` varchar(255),
	`last_name` varchar(255),
	`is_anonymized` boolean DEFAULT false,
	`anonymized_id` varchar(100),
	`age` int,
	`gender` varchar(50),
	`location` varchar(255),
	`category` varchar(100),
	`participation_date` timestamp,
	`participation_status` enum('active','completed','dropped') DEFAULT 'active',
	`notes` text,
	`consent_given` boolean DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `beneficiaries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `impact_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`application_id` int,
	`metric_name` varchar(255) NOT NULL,
	`metric_category` varchar(100),
	`metric_value` int NOT NULL,
	`metric_unit` varchar(100),
	`description` text,
	`reporting_period_start` timestamp,
	`reporting_period_end` timestamp,
	`data_source` varchar(255),
	`verification_status` enum('unverified','verified','audited') DEFAULT 'unverified',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `impact_metrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `impact_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`report_title` varchar(500) NOT NULL,
	`report_type` enum('annual','quarterly','project','donor','custom') NOT NULL,
	`application_id` int,
	`reporting_period_start` timestamp NOT NULL,
	`reporting_period_end` timestamp NOT NULL,
	`status` enum('draft','review','finalized','sent') NOT NULL DEFAULT 'draft',
	`content` text,
	`generated_by_ai` boolean DEFAULT false,
	`ai_prompt` text,
	`included_metrics` text,
	`target_audience` varchar(255),
	`language` enum('en','es','ca','eu') NOT NULL DEFAULT 'en',
	`pdf_url` text,
	`pdf_file_key` varchar(500),
	`created_by_user_id` int NOT NULL,
	`last_edited_by_user_id` int,
	`version` int NOT NULL DEFAULT 1,
	`parent_report_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`finalized_at` timestamp,
	`sent_at` timestamp,
	CONSTRAINT `impact_reports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `organization_profile` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organization_name` varchar(500) NOT NULL,
	`legal_name` varchar(500),
	`tax_id` varchar(100),
	`registration_number` varchar(100),
	`founded_year` int,
	`organization_type` varchar(100),
	`mission_statement` text,
	`vision_statement` text,
	`thematic_areas` text,
	`geographic_scope` text,
	`target_beneficiaries` text,
	`address` text,
	`city` varchar(255),
	`state` varchar(255),
	`country` varchar(100),
	`postal_code` varchar(20),
	`phone` varchar(50),
	`email` varchar(320),
	`website` varchar(500),
	`social_media` text,
	`logo_url` text,
	`logo_file_key` varchar(500),
	`staff_count` int,
	`volunteer_count` int,
	`annual_budget` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `organization_profile_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `report_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`template_name` varchar(255) NOT NULL,
	`template_type` varchar(100) NOT NULL,
	`description` text,
	`structure` text,
	`default_sections` text,
	`is_public` boolean DEFAULT false,
	`created_by_user_id` int,
	`language` enum('en','es','ca','eu') NOT NULL DEFAULT 'en',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `report_templates_id` PRIMARY KEY(`id`)
);
